# Generated by Django 5.2.17 on 2026-09-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('category', models.CharField(choices=[('food', 'Food'), ('transport', 'Transport'), ('shopping', 'Shopping'), ('health', 'Health'), ('other', 'Other')], max_length=20)),
                ('spent_on', models.DateField()),
            ],
            options={
                'ordering': ['-spent_on', '-id'],
            },
        ),
    ]
